# Generated by Django 4.2.10 on 2024-02-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('committee_name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Descrption')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('employee_name', models.CharField(max_length=100, verbose_name='Name')),
                ('emp_code', models.CharField(max_length=100, unique=True, verbose_name='Employee ID')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization')),
                ('type_of_employment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type of Employment')),
                ('category_of_employee', models.CharField(max_length=100, verbose_name='Category Of Employee')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleCommitteeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('committee_role_name', models.CharField(max_length=100, verbose_name='Name')),
                ('role_per_employee', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrption')),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolecommitteeinfo_committeeinfo', to='committee_app.committeeinfo')),
                ('employee', models.ManyToManyField(blank=True, null=True, related_name='rolecommitteeinfo_employeeinfo', to='committee_app.employeeinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
